version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:latest-sqlite

  kratos:
    image: oryd/kratos:latest-sqlite

  kratos-selfservice-ui-node:
    image: w6dio/kratos-selfservice-ui-node:latest
